config = {
'train_data_path': 'data/train.csv',
 'val_data_path': 'data/val.csv',
 'test_data_path': 'data/test.csv',
 'cat_cols': ['job',
  'marital',
  'education',
  'default',
  'housing',
  'loan',
  'contact',
  'day',
  'month',
  'campaign',
  'previous',
  'poutcome'],
 'num_cols': ['age', 'balance', 'duration', 'pdays'],
 'target': 'y',
 'batch_size': 256,
 'lr': 0.001,
 'n_epochs': 100,
 'patience': 5,
 'best_model_path': 'best_model.pth'
}